version: '3'

services:
  node-red:
    build: .
    container_name: local-bridge
    ports:
    - 3000:3000
    links:
      - "db:mysql"
    hostname: predictable-server
    restart: always
  db:
    image: mariadb
    container_name: bridge-db
    volumes:
    - test-mysql:/var/lib/mysql/
    restart: always

volumes:
  test-mysql:
